sudo: required
services:
  - docker

before_install:
  - docker build -t mmartin747/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mmartin747/react-test npm test -- --coverage

after_success:
  - docker build -t mmartin747/multi-client ./client
  - docker build -t mmartin747/multi-nginx ./nginx
  - docker build -t mmartin747/multi-server ./server
  - docker build -t mmartin747/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push mmartin747/multi-nginx ./nginx
  - docker push mmartin747/multi-client ./client
  - docker push mmartin747/multi-server ./server
  - docker push mmartin747/multi-worker ./worker